// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzrlrfkidaahceryoajc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6cmxyZmtpZGFhaGNlcnlvYWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTQxNjYsImV4cCI6MjA2NTU3MDE2Nn0.P2XkHw_ASQYSjb3LaGMLcwKBpikLnPKa-M2AMLyl45c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);